version: "3.5"
services:
  soft2_nginx:
    image: nginx:${NGINX_VERSION:-latest}
    ports:
      - "81:80"
    container_name: soft2_nginx
    networks:
      - frontend
      - backend
    depends_on:
      - soft2_mysql
      - soft2_django
    volumes:
      - ${PROJECT_ROOT}/:/code
      - ./docker/nginx/soft2.conf:/etc/nginx/conf.d/default.conf
    environment:
      document_root: "${PHP_ROOT}"

  soft2_mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    ports:
      - "3907:3306"
    volumes:
      - data:/var/lib/mysql
      - ./database_dump:/tmp/dumps
      - ./docker/mysql/custom:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: soft2_mysql
  
  soft2_django:
    build:
      context: './'
      dockerfile: Dockerfile.django
      args:
       PYTHON_VERSION: ${PYTHON_VERSION}
       DJANGO_ROOT: ${DJANGO_ROOT}
      target: dev
    command: "tail -f /dev/null"
    volumes:
      - ${DJANGO_ROOT}/:/code
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      DEBUG: "${DEBUG}"
      ENVIRONMENT_CONFIGURATION: "Dev"
    # ports:
    #   - "8004:8000"
    depends_on:
      - soft2_mysql
    container_name: soft2_django

networks:
  frontend:
  backend:
volumes:
    data: